# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up OpenJDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Check Java version
      run: java -version

    - name: maven-settings
      uses: s4u/maven-settings-action@v2
      with:
        servers: '[{"id": "vermicfintech-spi-kafdrop", "username": "${GITHUB_ACTOR}", "password": "${GITHUB_TOKEN}"}]'

    - name: Build with Maven
      run: mvn -B package  --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Use provided settings file with mvn command: -s .github/workflows/action-maven-settings.xml
# No deployment. Should later be deployed to docker register
