# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up OpenJDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Check Java version
      run: java -version

    - name: Setup Maven settings
      uses: s4u/maven-settings-action@v2.3.0
      with:
        repositories: '[{ "id": "central", "name": "Maven Central", "url": "https://repo1.maven.org/maven2", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },
          { "id": "vermicfintech-spi-kafdrop", "name": "VermicFinTech SPI KafDrop", "url": "https://maven.pkg.github.com/VermicFinTech/kafdrop", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },
          { "id": "vermicfintech-vericlear", "name": "VermicFinTech VeriClear", "url": "https://maven.pkg.github.com/VermicFinTech/vericlear", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'
        servers: '[{ "id": "vermicfintech-spi-kafdrop", "username": "$GITHUB_ACTOR", "password": "$GITHUB_TOKEN" },
          { "id": "vermicfintech-vericlear", "username": "$GITHUB_ACTOR", "password": "$GITHUB_TOKEN" }]'

    - name: Build with Maven
      run: mvn -B package --file pom.xml


# No deployment. Should later be deployed to docker register
