# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build KafDrop
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Set up OpenJDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Check Java version
      run: java -version


    - name: maven-settings
      uses: s4u/maven-settings-action@v2
      with:
        servers: '[{ "id": "vermicfintech-spi-kafdrop", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}" },
                   { "id": "vermicfintech-vericlear", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}" }]'

    - name: What doeas maven settings look like after
      run: cat /home/runner/.m2/settings.xml

    - name: Build with Maven
      run: mvn -B -X package --file pom.xml
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish KafDrop container
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Docker Build
      run: mvn -B docker:build --file pom.xml
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# Use provided settings file with mvn command: -s .github/workflows/action-maven-settings.xml
# No deployment. Should later be deployed to docker register
